"""input-from-web: type on your phone, inject into focused desktop app."""

try:
    from ._version import __version__  # generated by setuptools-scm at build time
except ImportError:  # running from a source checkout without build metadata
    __version__ = "0.1.0"